---
title: "Replication of Study X by Sample & Sample (20xx, Psychological Science)"
author: "Replication Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

### A short justification for your choice of experiment in terms of your research interests or research program. This justification should tell us why you chose this particular result.

My NSF GRFP application proposes the comparison of AI vision models and humans in judgments of object-scene context. 
The majority of paradigms in scene semantics utilize highly incongruent and congruent objects. 
I’ve been interested in investigating the full semantic spectrum by varying the level of semantic congruency on a continuous scale. 
Su et al., 2025 does this with a vector-space semantic model. 
In experiment 1b, they scored congruency on a continuous scale using word similarity and found a U-shape relationship (objects identified best when they fit the scene very well or very poorly). 
I’m choosing to replicate experiment 1b because it was preregistered, uses the same task as Experiment 1a (which ran online), and aims to treat congruency as continuous. 
The original study was run with Chinese speakers and a Chinese word model, so I’m curious if conducting it with English speakers at UCSD will also determine whether their U-shaped finding stays present. 
I also plan to score the same scene-object pairs with CLIP, DINO, and a large language model to determine which predicts participants’ accuracy best (my GRFP’s first aim).

### A description of the stimuli and procedures that will be required to conduct this experiment, and what the challenges will be (1-2 paragraphs).

The planned stimuli are photos of naturalistic real-world scenes taken from the SCEGRAM database (Öhlschläger & Võ, 2017), the Berlin Object in Scene database (Mohr et al., 2016), and the Internet. 
Congruency for the similarities between object-scene pairs will be determined with ConceptNet Numberbatch. 
During each trial, a fixation cross will appear for 800 to 1,000 ms, and the scene will be presented for 2.5 s. 
After a 500 ms pause with another fixation cross, two alternatives of the same kind of object will appear. 
One object will be from the scene recently presented, and the other is a different example of the same object. Participants press F or J on a keyboard to pick the one they saw. 
In addition, six catch trials will ask participants what kind of scene was shown to assess engagement. 
I’m planning to run around 60 people on SONA, since the authors’ power analysis requires at least 46.

The first challenge will be receiving access to the stimuli. The OSF page linked has the data and scripts, but the paper doesn’t say whether the images are open. I will need to work on getting the 76 scenes used and lure items from the authors. The second is language. The original study used the Chinese version of Numberbatch, and the stimuli were screened for familiarity with Chinese participants. English scores will likely shift some congruency values, and some objects may be less familiar or more familiar to UCSD students.

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

N/A

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
